django/board/urls.py
from django.urls import path
from . import views

app_name = "board"

urlpatterns = [
    path('',views.BoardIndexView.as_view(),name='home'),
    path('create/', views.BoardCreateView.as_view(), name='create'),
    path("<str:boardName>/",views.BoardListView.as_view(),name='aboard'),
    path('<str:boardName>/search/',views.BoardSearchView.as_view(),name='search'),
    path("<str:boardName>/post/",views.BoardPostView.as_view(),name="post"),
    path("<str:boardName>/<int:postID>/",views.PostDetailView.as_view(),name="detail"),
    path("<str:boardName>/<int:postID>/edit/",views.PostUpdateView.as_view(),name="update"),
    path("<str:boardName>/<int:postID>/delete/",views.PostDeleteView.as_view(),name="delete"),
    path("<str:boardName>/<int:postID>/<int:commentID>/delete/",views.CommentDeleteView.as_view(),name="CDelete"),
    path("<str:boardName>/<int:postID>/<int:commentID>/edit/",views.CommentUpdateView.as_view(),name="CEdit"),
    path("<int:postID>/like/",views.PostLikeView.as_view(),name="like"),
    path("<str:boardName>/recommend/",views.PostLikeSearchView.as_view(),name="likeSearch"),
]

django/userinfo/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("",views.userView, name= "user"),
    path("login/",views.LoginView.as_view(), name="login"),
    path("logout/",views.logoutView, name= "logout"),
    path("signup/",views.UserSignUpView.as_view(), name= "signup"),
    path("edit/<str:username>",views.UserUpdateInfo.as_view(), name="update"),
    path("edit/<str:username>/pw",views.UserUpdatePW.as_view(), name="updatePW"),
    path("edit/<str:username>/off",views.UserUpdateOFF.as_view(), name="off"),
    path("<str:nickname>",views.UserInfoView.as_view(), name="userInfo"),
]

django/userinfo/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    nickname = models.CharField(max_length=24, unique=True)
    username = models.CharField(max_length=24, unique=True)
    email = models.EmailField(unique= True)
    
    first_name = None
    last_name = None
    
    class Meta:
        ordering = ['id']
    
    def __str__(self):
        return self.username

django/userinfo/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import PasswordChangeForm,UserCreationForm

class LoginForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"아이디 입력", 'class':'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"비밀번호 입력", 'class':'form-control'}))
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for key, field in self.fields.items():
            field.label = ""
    
    class Meta:
        model = User
        fields = ['username','password']

class SignUserForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"아이디 입력", 'class':'form-control'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"비밀번호 입력", 'class':'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"비밀번호 입력 확인", 'class':'form-control'}))
    nickname = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"닉네임 입력", 'class':'form-control'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={"placeholder":"이메일주소", 'class':'form-control'}))
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for key, field in self.fields.items():
            field.label = ""
    
    '''def save(self,commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user
    '''
    class Meta:
        model = User
        fields = ['username','password1', 'password2','nickname', 'email']
        
class UpdateForm(forms.ModelForm):
    nickname = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"변경할 닉네임 입력", 'class':'form-control'}),label="변경할 닉네임")
    email = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"변경할 이메일 주소 입력", 'class':'form-control'}),label="변경할 이메일 주소")
    class Meta:
        model = User
        fields = ['nickname','email']
        
class UpdateFormOFF(forms.ModelForm):
    class Meta:
        model = User
        fields = ['is_active']

class UpdatePWForm(PasswordChangeForm):
    old_password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder":"현재 비밀번호 입력", 'class':'form-control'}))
    new_password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder":"새로운 비밀번호 입력", 'class':'form-control'}))
    new_password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder":"새로운 비밀번호 확인 입력", 'class':'form-control'}))
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for key, field in self.fields.items():
            field.label = ""
    
    def clean(self):
        old_password = self.cleaned_data.get("old_password")
        new_password1 = self.cleaned_data.get("new_password1")

        if old_password == new_password1:
            self.add_error(
                "old_password",
                forms.ValidationError("이전 비밀번호와 입력된 새로운 비밀번호이 같습니다.")
            )
        else:
            return self.cleaned_data

django/userinfo/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.urls import reverse_lazy
from django.contrib import messages

from .models import User
from .forms import *
from board.models import *
from django.views.generic import DetailView, ListView, UpdateView,CreateView,FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin

def userView(request):
    return render(request,'userinfo/user.html')

class LoginView(FormView):
    form_class = LoginForm
    template_name = 'userinfo/login.html'
    
    def post(self,request):
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username = username, password = password)

        if user is not None and user.is_active:
            login(request,user)
            messages.success(request,f"환영합니다. {username}, 성공적으로 로그인 되었습니다.")
            return redirect("board:home")
        else:
            messages.error(request,"아이디와 비밀번호가 일치하지 않거나 존재하지 않습니다.")
            return redirect("user:login")
        

def logoutView(request):
    logout(request)
    messages.success(request,"성공적으로 로그아웃 되었습니다.")
    return redirect("user:login")

class UserSignUpView(SuccessMessageMixin,CreateView):
    model = User
    form_class = SignUserForm
    template_name = 'userinfo/signup.html'
    success_url= reverse_lazy('user:login')
    success_message = "계정이 성공적으로 생성되었습니다. 로그인 페이지로 이동합니다."

class UserUpdateInfo(LoginRequiredMixin,UpdateView):
    model = User
    form_class = UpdateForm
    success_url = reverse_lazy('user:user')
    template_name = 'userinfo/update.html'
    context_object_name = "theUser"

    def form_valid(self,form):
        messages.success(self.request,"정보가 성공적으로 변경되었습니다.")
        return super().form_valid(form)
     
    def get_object(self):
        return get_object_or_404(User,username=self.kwargs["username"])

class UserUpdatePW(PasswordChangeView):
    template_name = 'userinfo/updatePW.html'
    form_class = UpdatePWForm
    success_url = reverse_lazy("user:user")
    
    def form_valid(self, form):
        form.save()
        update_session_auth_hash(self.request,form.user)
        messages.success(self.request,"비밀번호가 성공적으로 변경되었습니다.")
        return super().form_valid(form)
    
class UserUpdateOFF(LoginRequiredMixin,UpdateView):
    model = User
    form_class = UpdateFormOFF
    template_name = 'userinfo/updateOFF.html'
    
    def get_object(self):
        return get_object_or_404(User,username=self.kwargs["username"])
    
    def form_valid(self, form) :
        user = self.object
        user.is_activated = False
        user.save()
        messages.success(self.request,"해당 계정이 정지되었습니다. 이용해주셔서 감사합니다.")        
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('user:logout')   

class UserInfoView(DetailView):
    model = User
    template_name = "userinfo/userinfo_base.html"
    pk_url_kwarg = "UID"
    context_object_name = "theUser"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        who = User.objects.get(nickname=self.kwargs["nickname"])
        post = Post.objects.filter(PostAuthor=who)
        comments = Comment.objects.filter(CommentAuthor=who)
        context["posts"] = post[::-1][:15]
        context["comments"] = comments[::-1][:15]
        return context
    
    def get_object(self):
        return get_object_or_404(User,nickname=self.kwargs["nickname"])


'''
def loginView(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username = username, password = password)

        if user is not None and user.is_active:
            login(request,user)
            return redirect("board:home")
        else:
            messages.error(request,"아이디와 비밀번호가 일치하지 않거나 존재하지 않습니다.")
            return redirect("user:login")
    else:
        form = LoginForm()
        return render(request,"userinfo/login.html", {'form' : form})

def signupView(request):
    if request.method == "POST":
        form = SignUserForm(request.POST)
          
        if form.is_valid():
            new_user = User.objects.create_user(**form.cleaned_data)
            return redirect("user:login")
        else:
            print("뭔가 잘못됨")
    else:
        form = SignUserForm()
        return render(request,"userinfo/signup.html",{'form' : form})
'''

django/templates/userinfo/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% if request.user.is_authenticated%}
<div class="container"style="float: none; margin:100 auto;">
    <div class="col-md-3" style="float: none; margin:0 auto;">
        <p>잘못된 접근입니다.</p>
        <input type=button value="Previous Page" onClick="javascript:history.go(-1);">
    </div>
</div>
{%else%}

<div class="form-group text-center" style="float: none; margin:100 auto;">
    <div class="col-md-3" style="float: none; margin:0 auto;">
        <form action="" method="POST" class="form-signin">
            <h1 class="h3  mt-5 mb-3 font-weight-normal">로그인</h1>
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-lg mt-3 btn-primary btn-block">로그인</button>
        </form>
        <a class="btn mt-3 btn-lg btn-primary btn-block" href="{% url 'user:signup' %}">회원가입</a>
    </div>
</div>
{% endif %}
{% endblock %}

django/templates/userinfo/signup.html
{% extends 'base.html'%}
{%load static %}

{% block content %}
<div class="text-center" style="margin:100 auto;">
    <div class="col-md-3 mt-5" style="float: none; margin:0 auto;">
        <form action="" method="POST" class="form-group" >
            {% csrf_token %}
            {{ form.as_p }}  
            <button type="submit" class="btn btn-lg mt-3 btn-primary btn-block">완료</button>
        </form>
    </div>
</div>
{% endblock %}

django/templates/userinfo/update.html
{% extends 'base.html'%}
{%load static %}

{% block content %}
    <div class="text-center" style="margin:100 auto;">
        <div class="col-md-3 mt-5" style="float: none; margin:0 auto;">
            <form action="" method="POST" class="form-group" >
                {% csrf_token %}
                {{ form.as_p }}  
                <button type="submit" class="btn btn-lg mt-3 btn-primary btn-block">수정하기</button>
            </form>
        <a type="submit" class="btn btn-lg mt-3 btn-primary btn-block" href="{% url 'user:updatePW' theUser.username %}">비밀번호 변경하러 가기</a>
            <div style="margin-top:50px" >
                <form class="form-group"  action="{% url 'user:off' theUser.username %}" method="POST" onsubmit="return confirm('정말로 정지 할까요?')">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-lg mt-3 btn-danger btn-block">계정 정지 하기</button>
                    <div class="form-text">계정 삭제시에 게시글과 댓글들은 자동적으로 지워지지 않으며, 계정 정지는 되돌릴 수 없습니다.</div> 
                </form>
            </div>
        </div>
    </div>
{% endblock %}

django/templates/userinfo/updateOFF.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

django/templates/userinfo/updatePW.html
{% extends 'base.html'%}
{%load static %}

{% block content %}
<div class="form-group text-center mt-5" style="float: none; margin:100 auto;">
    <div class="col-md-3" style="float: none; margin:0 auto;">
        <form action="" method="POST" class="form-signin">
            <h1 class="h3  mt-5 mb-3 font-weight-normal">비밀번호 변경</h1>
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-lg mt-3 btn-primary btn-block">변경하기</button>
        </form>
    </div>
</div>
{% endblock %}

django/templates/userinfo/user.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% if user.is_authenticated %}
<div class="form container">
    <label for="ID" class="form-label">계정 ID</label>
    <input class="form-control" type="text" placeholder="{{user.username}}" id="ID" aria-label="Disabled input example" disabled>
    <label for="nickname" class="form-label">계정 닉네임</label>
    <input class="form-control" type="text" placeholder="{{user.nickname}}" id="nickname" aria-label="Disabled input example" disabled>
    <label for="email" class="form-label">email</label>
    <input class="form-control" type="text" placeholder="{{user.email}}" id="email" aria-label="Disabled input example" disabled>
    <label for="date_join" class="form-label">계정생성일</label>
    <input class="form-control" type="text" placeholder="{{user.date_joined}}" id="date_joined" aria-label="Disabled input example" disabled>

    <div class="btn-group float-right mt-3" role="group">
        <button type="button" class="btn btn-outline-primary" onclick = "location.href = '{% url 'user:userInfo' user.nickname %}' ">활동내역</button>
        <button type="button" class="btn btn-outline-primary" onclick = "location.href = '{% url 'user:update' user.username%}' ">정보변경</button>
        <button type="button" class="btn btn-outline-primary" onclick = "location.href = '{% url 'user:logout' %}' ">로그아웃</button>
    </div>
</div>

{% else %}
    로그인 해야하는 서비스 입니다.<br>
    <a href="{% url 'user:login' %}">로그인 하기</a>
{% endif %}

{% endblock %}

django/templates/userinfo/userinfo_base.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<body>
    <p class="h1 mt-3 text-center">{{theUser.nickname}}님의 최근 기록</p>
    <div class="container-md col-6" >
        <div>
            <p class="h5 bg-light">최근 작성한 15 포스트</p>
            <ul class="list-group">
            {% if theUser %}
                {% for info in posts %}
                <li class="list-group-item">
                    <a href="{% url 'board:detail' boardName=info.board.subject postID=info.pk %}">
                    <span class="badge rounded-pill bg-dark" style="color:white">{{info.board.subject}} 게시판</span>
                    <span> {{info}}[{{info.comments}}] </span>
                    <span style="font-size: 0.7em ; color:black">{{info.writeDate}}</span>
                    </a>
                </li>
            {% endfor %}
            </ul>
            {% else %}
            {% endif %} 
        </div>
    
        <div>
            <p class="h5 bg-light">최근 작성한 15 댓글</p>
            <ul class="list-group">
            {% if theUser %}
                {% for info in comments %}
                    <li class="list-group-item">
                        <a href="{% url 'board:detail' boardName=info.post.board.subject postID=info.post.pk %}">
                        <span class="badge rounded-pill bg-dark" style="color:white">{{info.post.board.subject}} 게시판</span>
                        <span>{{info.contents}}</span>
                        <span style="font-size: 0.7em ; color:black">{{info.writeDate}}</span>
                        </a>
                    </li>
            {% endfor %}
            </ul>
            </div>
            {% else %}
            {% endif %}
        </div>
    </div>
{% endblock %}