django/board/urls.py
from django.urls import path
from . import views

app_name = "board"

urlpatterns = [
    path('',views.BoardIndexView.as_view(),name='home'),
    path('create/', views.BoardCreateView.as_view(), name='create'),
    path("<str:boardName>/",views.BoardListView.as_view(),name='aboard'),
    path('<str:boardName>/search/',views.BoardSearchView.as_view(),name='search'),
    path("<str:boardName>/post/",views.BoardPostView.as_view(),name="post"),
    path("<str:boardName>/<int:postID>/",views.PostDetailView.as_view(),name="detail"),
    path("<str:boardName>/<int:postID>/edit/",views.PostUpdateView.as_view(),name="update"),
    path("<str:boardName>/<int:postID>/delete/",views.PostDeleteView.as_view(),name="delete"),
    path("<str:boardName>/<int:postID>/<int:commentID>/delete/",views.CommentDeleteView.as_view(),name="CDelete"),
    path("<str:boardName>/<int:postID>/<int:commentID>/edit/",views.CommentUpdateView.as_view(),name="CEdit"),
    path("<int:postID>/like/",views.PostLikeView.as_view(),name="like"),
    path("<str:boardName>/recommend/",views.PostLikeSearchView.as_view(),name="likeSearch"),
]

django/userinfo/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("",views.userView, name= "user"),
    path("login/",views.LoginView.as_view(), name="login"),
    path("logout/",views.logoutView, name= "logout"),
    path("signup/",views.UserSignUpView.as_view(), name= "signup"),
    path("edit/<str:username>",views.UserUpdateInfo.as_view(), name="update"),
    path("edit/<str:username>/pw",views.UserUpdatePW.as_view(), name="updatePW"),
    path("edit/<str:username>/off",views.UserUpdateOFF.as_view(), name="off"),
    path("<str:nickname>",views.UserInfoView.as_view(), name="userInfo"),
]

django/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{%  static 'css/bootstrap.min.css' %}" />
    <style>     
        #logo{
            filter:invert(100%);
        }
    </style>
</head>
<body class="d-flex flex-column min-vh-100">

    {% include "header.html" %}
    {% include "message.html" %}
    {% block content %}
    {% endblock %}
    {% include "footer.html" %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

django/templates/footer.html
{% load static %}
<footer class="py-3 bg-dark mt-auto">
    <div class="container px-4"><p class="m-0 text-center text-white">Copyright &copy; MyCommunity 2022, Kim Sung Gwang</p></div>
</footer>

django/templates/header.html
{% load static %}

<header class="navbar sticky-top navbar-expand-md navbar-dark bg-dark bg-gradient">
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark bg-gradient">
    <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static 'assets/line.svg' %}" width="30" height="30" class="d-inline-block align-top" alt="" class="icon" id="logo">
            MyCommunity</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        
        {% if request.user.is_authenticated %}
        <ul class="navbar-nav flex-row flex-wrap ms-md-auto">
            <li class="nav-item dropdown col-6 col-md-auto ">
                <a class="nav-link p-2 dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{request.user.nickname}}
                </a>
            <div class="dropdown-menu .dropdown-menu-end">
                <a class="dropdown-item" href="{% url 'user:user' %}">
                    <img src="{% static 'assets/person-fill.svg' %}" width="15" height="15" class="d-inline-block" alt="" class="icon"> 계정정보</a>
                <a class="dropdown-item" href="{% url 'user:userInfo' request.user.nickname %}"> 
                    <img src="{% static 'assets/list-task.svg' %}" width="15" height="15" class="d-inline-block" alt="" class="icon"> 활동내역</a>
                <a class="dropdown-item" href="{% url 'user:update' user.username%}">
                    <img src="{% static 'assets/pencil-square.svg' %}" width="15" height="15" class="d-inline-block" alt="" class="icon"> 정보변경</a>
                <a class="dropdown-item" href="{% url 'user:logout' %}">
                    <img src="{% static 'assets/door-closed-fill.svg' %}" width="15" height="15" class="d-inline-block" alt="" class="icon"> 로그아웃</a>
            </div>
            </li>
        </ul>
        {% else %}
        <ul class="navbar-nav flex-row flex-wrap ms-md-auto">
            <li class="nav-item col-6 col-md-auto">
                <a class="nav-link p-2" href="{% url 'user:login' %}">로그인 하기</a>

            </li>

        </ul>

        {% endif %}

        <ul class="navbar-nav flex-row flex-wrap bd-navbar-nav pt-2 py-md-0">
        
            <li class="nav-item">
                <a class="nav-link" href="{% url 'board:home' %}">게시판홈</a>
            </li>
        
        </ul>
        
    </div>
  </nav>
</header>

django/templates/index.html
{%extends "base.html" %}
{% load static %}

{% block content %}
<!-- Header-->
<header class="bg-primary bg-gradient text-white">
    <div class="container px-4 text-center">
        <h1 class="fw-bolder">안녕하세요, MyCommunity 입니다</h1>
        <p class="lead">이 프로젝트의 홈페이지이자, Readme 페이지입니다</p>
    </div>
</header>
<!-- About section-->
<section id="about">
    <div class="container px-4">
        <div class="row gx-4 justify-content-center">
            <div class="col-lg-8">
                <h2>무엇을 소개하나요</h2>
                <p class="lead">이 페이지는 인터넷 커뮤니티 사이트들을 클론코딩한 프로젝트, MyCommunity의 소개와 만드는 과정 등을 담고 있습니다. 이 페이지는 아직 미완성입니다. <span class="bg-warning">상단 배너의 링크들을 클릭하여 이 페이지를 빠져나갈 수 있습니다.</span></p>
            </div>
        </div>
    </div>
</section>
<!-- Services section-->
<section class="bg-light" id="services">
    <div class="container px-4">
        <div class="row gx-4 justify-content-center">
            <div class="col-lg-8">
                <h2>구현한 기능들</h2>
                <p class="lead">구현한 기능은 커뮤니티의 기본적인 기능인 두가지인 User 모델과 게시판 모델 구현입니다.</p>
                <ul class="list-group">
                    <li class="list-group-item">
                        User : CRUD
                    </li>
                    <li class="list-group-item">
                        Board : 게시판 CRUD
                    </li>
                    <li class="list-group-item">
                        Board : 포스트 CRUD
                    </li>
                    <li class="list-group-item">
                        Board : 댓글 CRUD
                    </li>
                    <li class="list-group-item">
                        Board : 검색
                    </li>
                    <li class="list-group-item">
                        Board : 추천
                    </li>
                </ul>
                <p class="mt-1">
                    커뮤니티의 기본적인 기능을 구현하고자 힘썼습니다. User 모델의 경우 django에서 권장하는대로 django.auth에서 지원하는 AbstractUser을 상속받은 후 auth 함수들을 이용하여 구성하였습니다.
                    <span class="text-white bg-danger">공부 부족으로 인해서 Ajax을 사용하지 않아 비동기식 처리는 지원하지 않습니다. 또한 모바일 환경을 고려하여 구성하지 못했습니다.</span>
                </p>
            </div>
        </div>
    </div>
</section>
<!-- Contact section-->
<section id="contact">
    <div class="container px-4">
        <div class="row gx-4 justify-content-center">
            <div class="col-lg-8">
                <h2>어떻게 구현했나요</h2>
                <img src="media/bone.png"  style="width: 25vw; min-width: 140px; display: block; margin: 0px auto; ;" alt="My Image">
                <p>위 이미지와 같이, 이 프로젝트는 Python Django를 기반으로 만들어졌으며 DB는 MYSQL을, 이 사이트를 웹상에 배포하기 위해서 AWS, Docker, Nginx, Gunicorn를 사용했으며, 그 외에도 버전관리를 위해 Git을, 웹페이지는 Bootstrap을 활용하였습니다. </p>
                <P>django로 만들어진 app과 gunicorn + nginx, mysql 을 docker-compose로 한데 묶어 AWS에서 실행하는 것으로 이 프로젝트를 배포 할 수 있었습니다.</P>
            </div>
        </div>
    </div>
</section>
{% endblock %}        

django/templates/message.html
{% load static %}
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}" style="text-align:center">
        {{ message }}
    </div>
    {% endfor %}
{% endif %}

django/templates/posts.html
{% extends "board/board_template.html" %}

{% block content %}
<div>
  <main class="col-9 py-md-3 pl-md-5 bd-content" role="main">
    <table class="table">
        <thead class="rowTop">
            <th class="rowNum">
                글번호
            </th>
            <th class="rowTitle">
                제목
            </th>
            <th class="rowAuthor">
                작성자
            </th>
            <th class="rowTime">
                작성시간
            </th>
            <th class="rowViews">
                조회
            </th>
            <th class="rowRate">
                추천
            </th>
        </thead>
    
    {% if posts %}
        <tbody>
        {% for post in posts %}
            <tr>
                <td class="rowNum">
                    {{post.pk}}
                </td>
                <td class="rowTitle">
                    <a href="{% url 'board:detail' boardName=board.subject postID=post.pk  %}">{{post.title}}   [{{post.comments}}]</a>
                </td>
                <td class="rowAuthor">
                    <a href="{% url 'user:userInfo' post.PostAuthor.nickname %}">{{post.PostAuthor.nickname}}</a> 
                </td>
                <td class="rowTime">
                    {{post.writeDate}}
                </td>
                <td class="rowViews">
                    {{post.views}}
                </td>
                <td class="rowRate">
                    {{post.count_like}}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
    {% endif %}
    <br>
  </main>
    <div class="container-fluid">
        <div class="row flex-nowrap">
            <div class="col-3 bd-sidebar">
                
                
            </div>
        </div>
    </div>
</div>



{% endblock %}

django/templates/search.html
{% load static%}

<div>
    <form class="form-inline justify-content-center" method="GET" action="{% url 'board:search' board.subject %}">
        <select class="custom-select" id="type" name="t">
            <option value="wide">제목 + 내용</option>
            <option value="title">제목</option>
            <option value="author">글쓴이</option>
        </select>
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="c">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">검색</button>
    </form>
</div>

django/templates/temp_index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'user:user' %}">유저페이지로 가기 </a><br>
    <a href="{% url 'board:home' %}">게사판으로 가기 </a>
</body>
</html>