django/board/urls.py
from django.urls import path
from . import views

app_name = "board"

urlpatterns = [
    path('',views.BoardIndexView.as_view(),name='home'),
    path('create/', views.BoardCreateView.as_view(), name='create'),
    path("<str:boardName>/",views.BoardListView.as_view(),name='aboard'),
    path('<str:boardName>/search/',views.BoardSearchView.as_view(),name='search'),
    path("<str:boardName>/post/",views.BoardPostView.as_view(),name="post"),
    path("<str:boardName>/<int:postID>/",views.PostDetailView.as_view(),name="detail"),
    path("<str:boardName>/<int:postID>/edit/",views.PostUpdateView.as_view(),name="update"),
    path("<str:boardName>/<int:postID>/delete/",views.PostDeleteView.as_view(),name="delete"),
    path("<str:boardName>/<int:postID>/<int:commentID>/delete/",views.CommentDeleteView.as_view(),name="CDelete"),
    path("<str:boardName>/<int:postID>/<int:commentID>/edit/",views.CommentUpdateView.as_view(),name="CEdit"),
    path("<int:postID>/like/",views.PostLikeView.as_view(),name="like"),
    path("<str:boardName>/recommend/",views.PostLikeSearchView.as_view(),name="likeSearch"),
]

django/userinfo/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("",views.userView, name= "user"),
    path("login/",views.LoginView.as_view(), name="login"),
    path("logout/",views.logoutView, name= "logout"),
    path("signup/",views.UserSignUpView.as_view(), name= "signup"),
    path("edit/<str:username>",views.UserUpdateInfo.as_view(), name="update"),
    path("edit/<str:username>/pw",views.UserUpdatePW.as_view(), name="updatePW"),
    path("edit/<str:username>/off",views.UserUpdateOFF.as_view(), name="off"),
    path("<str:nickname>",views.UserInfoView.as_view(), name="userInfo"),
]

django/templates/post/post_base.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% if request.user != thePost.PostAuthor %}
    {{thePost.UpdateViews}}
{% endif %}
<div class="navi pl-md-7">
    <ul class="btn-group" role="group"> 
        <button type="submit" class="btn btn-primary" onclick="location.href='{% url 'board:aboard' thePost.board.subject %}'">목록</button>
        <button type="submit" class="btn btn-primary" onclick="location.href='{% url 'board:post' thePost.board.subject %}'">글쓰기</button>
        {% if thePost.PostAuthor == request.user%}
        <button type="submit" class="btn btn-primary" onclick="location.href='{% url 'board:update' boardName=thePost.board.subject postID=thePost.PostID %}'">수정</button>
        <form action="{% url 'board:delete' boardName=thePost.board.subject postID=thePost.PostID %}" method="POST" onsubmit="return confirm('정말로 삭제할까요?')">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">삭제</button>
        </form>
        {%else%}
        {%endif%}
    </ul>
</div>

<div class="container col-12">
    <main class="center-block" role="main">
        <table class="table table-bordered overflow-auto">
            <tr>
                <td class="h3" colspan="4">{{thePost.title}}</td>
            </tr>
            <tr>
                <td><a href="{% url 'user:userInfo' thePost.PostAuthor.nickname %}">{{thePost.PostAuthor.nickname}}</a></td>
                <td>조회수 {{thePost.views}} </td>
                <td>추천수 {{thePost.count_like}} </td>
                <td>작성일 {{thePost.writeDate}} </td>
            </tr>
            <tr>
                <td style="padding-bottom: 10%;" colspan="4">{{thePost.contents | safe }} </td>
            </tr>
            <tr><td  class="text-center" style="border-top: hidden;" colspan="4">
                <form action="{% url 'board:like' postID=thePost.PostID %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-outline-primary"><span>
                        <img src="{% static 'assets/star.svg' %}" width="15" height="15" class="d-inline-block mr-2" alt="" class="icon">
                    </span>
                    {{thePost.count_like}}</button>
                </form>
                </td>
            </tr>
        </table>
        
        
        {% if comments %}
        <div class="col-12 table-bordered">
                {% for com in comments %}
                <div class="container-fluid table-bordered my-2">
                    <div>
                        <a href="{% url 'user:userInfo' com.CommentAuthor.nickname  %}">{{com.CommentAuthor.nickname}}</a>
                    </div>
                    <div style="width:auto">
                        {{com.contents}}
                    </div>
                    <div >
                        <span style="font-size: 0.7em;">({{com.writeDate}})</span>
                    </div>

                    {% if com.CommentAuthor == request.user %}
                    <div class="btn-group">
                        <div>
                            <button class="btn btn-primary" data-toggle="collapse" data-target="#edit{{com.CommentID}}" aria-expanded="false">수정</button>
                            <div id="edit{{com.CommentID}}" class="collapse">
                                <form action="{% url 'board:CEdit' boardName=com.post.board.subject postID=com.post.PostID commentID=com.CommentID %}" method="POST">
                                    {% csrf_token %}
                                    {{form}}
                                    <button type="submit" class="btn btn-primary">수정완료</button>
                                </form>
                            </div>
                        </div> 
                        <div>
                            <form action="{% url 'board:CDelete' boardName=com.post.board.subject postID=com.post.PostID commentID=com.CommentID %}" method="POST" onsubmit="return confirm('정말로 삭제할까요?')">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger" >삭제</button>
                            </form>
                        </div>      
                    </div>
                    {%endif%}
                </div>
            {%endfor%}
        </div>
        {% else %}
        {% endif %}
    
       <div>
        {% if request.user.is_authenticated %}
            <form action="" method="POST" style="white-space:nowrap;">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn float-right mt-3 btn-primary">댓글달기</button>
            </form>
        {% else %}
            <div>
                <a href="{% url 'user:login' %}">로그인이 필요합니다</a>
            </div>
        {% endif %}
        </div>  
    </main>
</div>
{% endblock %}

django/templates/post/post_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="삭제하기">
    </form>
</body>
</html>

django/templates/post/post_edit.html
{% extends 'base.html'%}
{%load static %}

{% block content %}
<div class="form-group text-center" >
    <div class="col-md-3">
        <form action="" method="POST" class="form-signin">
            <h1 class="h3  mt-5 mb-3 font-weight-normal">포스트 작성</h1>
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-lg mt-3 btn-primary btn-block">수정하기</button>
            <input type=button class="btn btn-lg mt-3 btn-primary btn-block" value="취소하기" onClick="javascript:history.go(-1);">
        </form>
    </div>
</div>
{% endblock %}

django/templates/post/post_like.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>