django/board/urls.py
from django.urls import path
from . import views

app_name = "board"

urlpatterns = [
    path('',views.BoardIndexView.as_view(),name='home'),
    path('create/', views.BoardCreateView.as_view(), name='create'),
    path("<str:boardName>/",views.BoardListView.as_view(),name='aboard'),
    path('<str:boardName>/search/',views.BoardSearchView.as_view(),name='search'),
    path("<str:boardName>/post/",views.BoardPostView.as_view(),name="post"),
    path("<str:boardName>/<int:postID>/",views.PostDetailView.as_view(),name="detail"),
    path("<str:boardName>/<int:postID>/edit/",views.PostUpdateView.as_view(),name="update"),
    path("<str:boardName>/<int:postID>/delete/",views.PostDeleteView.as_view(),name="delete"),
    path("<str:boardName>/<int:postID>/<int:commentID>/delete/",views.CommentDeleteView.as_view(),name="CDelete"),
    path("<str:boardName>/<int:postID>/<int:commentID>/edit/",views.CommentUpdateView.as_view(),name="CEdit"),
    path("<int:postID>/like/",views.PostLikeView.as_view(),name="like"),
    path("<str:boardName>/recommend/",views.PostLikeSearchView.as_view(),name="likeSearch"),
]

django/userinfo/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("",views.userView, name= "user"),
    path("login/",views.LoginView.as_view(), name="login"),
    path("logout/",views.logoutView, name= "logout"),
    path("signup/",views.UserSignUpView.as_view(), name= "signup"),
    path("edit/<str:username>",views.UserUpdateInfo.as_view(), name="update"),
    path("edit/<str:username>/pw",views.UserUpdatePW.as_view(), name="updatePW"),
    path("edit/<str:username>/off",views.UserUpdateOFF.as_view(), name="off"),
    path("<str:nickname>",views.UserInfoView.as_view(), name="userInfo"),
]

django/board/models.py
from django.db import models
from django.urls import reverse
from userinfo.models import User

# Create your models here.

class Board(models.Model):
    BoardID = models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='BID')
    subject = models.CharField(max_length=60, unique=True)
    context = models.CharField(max_length=100)
    principal = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    isActivate = models.BooleanField(default=True)
    
    def __str__(self):
        return f'{self.pk} : {self.subject}'

    def get_absolute_url(self):
        return reverse('board-detail-view',args=[self.subject])
    

class Post(models.Model):
    PostID = models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='PID')
    PostAuthor = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    board = models.ForeignKey(Board,on_delete=models.CASCADE)
    
    title = models.CharField(max_length=50)
    contents = models.TextField()
    
    writeDate = models.DateTimeField(auto_now_add=True)
    modifyDate = models.DateTimeField(auto_now=True)
    
    views = models.PositiveIntegerField(default=0)
    comments = models.PositiveIntegerField(default=0)
    
    like_user = models.ManyToManyField(User,through='Like',through_fields=('post','user'),related_name='likes')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail-view',args=[self.pk])
    
    def count_like(self):
        return self.like_user.count()
    
    @property
    def UpdateViews(self):
        self.views += 1
        self.save()
        return ""

class Like(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user}이 {self.post} 게시물을 추천함'

class Comment(models.Model):
    CommentID = models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='CID')
    CommentAuthor = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    parent =  models.ForeignKey('self',on_delete=models.SET_NULL,null=True,blank=True)
    contents = models.TextField(max_length= 200)

    writeDate = models.DateTimeField(auto_now_add=True)
    modifyDate = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        if len(self.contents) >= 20:
            return self.contents[:20]
        else:
            return self.contents

django/board/forms.py
from cProfile import label
from django import forms
from .models import *

from django_summernote.widgets import SummernoteWidget

class boardForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for key, field in self.fields.items():
            field.label = ""
    
    class Meta:
        model = Board
        fields = ['subject','context']
        widgets = {
            'subject' : forms.TextInput(attrs={
                "placeholder":"게시판 이름을 입력해주세요",
                'class':'form-control',
                }),
            
            'context' : forms.Textarea(attrs={
                "placeholder":"게시판 설명을 입력해주세요", 
                'class':'form-control'
                })
        }
class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for key, field in self.fields.items():
            field.label = ""
    
    class Meta:
        model = Post
        fields = ['title','contents']
        widgets = {
            'title' : forms.TextInput(attrs={
                "placeholder":"제목을 입력해주세요",
                'class':'form-control mb-3',
            }),
            'contents' : SummernoteWidget()
        }

class CommentForm(forms.ModelForm):
    contents = forms.CharField(widget=forms.Textarea(attrs={"placeholder":"댓글을 입력해주세요", 'class':'form-control','rows': 3, 'style':'resize:none;'}))
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for key, field in self.fields.items():
            field.label = ""
    
    class Meta:
        model = Comment
        fields = ['contents']
        widgets = {
            'contents' : forms.Textarea(attrs={
                "placeholder":"댓글을 입력해주세요",
                'class':'form-control',
            }),
        }

django/board/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import ListView,CreateView,DetailView,UpdateView,DeleteView,TemplateView
from rest_framework.mixins import UpdateModelMixin
from django.views.generic.edit import FormMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.db.models import Q,Count

from .models import Board
from .forms import *
from userinfo.models import User
from userinfo.utils import *
# Create your views here.

class BoardIndexView(ListView):
    model = Board
    context_object_name = 'BoardList'
    template_name = 'board/board_list.html'
    
    def get_queryset(self):
        return Board.objects.filter(isActivate = True)
    
class BoardListView(ListView):
    model = Post
    context_object_name = 'posts'
    paginate_by = 20
    template_name = 'board/board_View.html'
    ordering = ['-PostID']
    page_kwarg = 'page'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['board'] = Board.objects.get(subject = self.kwargs['boardName'])
        paginator = context['paginator']
        page_numbers_range = 10
        max_index = len(paginator.page_range)
        
        page = self.request.GET.get('page')
        current_page = int(page) if page else 1
        
        start_index = int((current_page -1 ) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index
        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range
        
        return context
    
    def get_queryset(self):
        board = Board.objects.get(subject=self.kwargs['boardName'])
        
        return Post.objects.filter(board= board).order_by('-PostID')

class BoardCreateView(LoginRequiredMixin,CreateView):
    model = Board
    form_class = boardForm
    template_name = 'board/create.html'
    
    def form_valid(self, form):
        newBoard = form.save(commit=False)
        newBoard.principal = self.request.user   
        newBoard.save()
        messages.success(self.request, "게시판이 성공적으로 생성되었습니다")
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('board:aboard',kwargs={'boardName':self.object.subject})

class BoardPostView(LoginRequiredMixin,CreateView):
    model = Post
    form_class = PostForm
    context_object_name = 'Board'
    template_name = 'board/postCreate.html'
    
    def form_valid(self, form):
        form.instance.PostAuthor = self.request.user
        form.instance.board = Board.objects.get(subject=self.kwargs['boardName'])
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('board:detail', kwargs={'boardName':self.object.board.subject, 'postID':self.object.PostID})
    
class BoardSearchView(ListView):
    model = Post
    template_name = 'board/board_search.html'
    context_object_name = 'posts'
    paginate_by = 20
    
    def get_queryset(self):
        search_type = self.request.GET.get('t','')
        search_content = self.request.GET.get('c','')
        post_list = Post.objects.order_by('-PostID')
        
        if search_content :
            if search_type == 'wide':
                searched_list = post_list.filter(Q (title__icontains= search_content) 
                                               | Q (contents__icontains = search_content))
            elif search_type == 'title':
                searched_list = post_list.filter(Q (title__icontains= search_content))
            
            elif search_type == 'author':
                searched_list = post_list.filter(Q (PostAuthor__nickname= search_content))
            
            return searched_list
        else:
            messages.error(self.request,'잘못된 접근입니다')
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['board'] = Board.objects.get(subject = self.kwargs['boardName'])
        search_type = self.request.GET.get('t','')
        search_content = self.request.GET.get('c','')
        
        paginator = context['paginator']
        page_numbers_range = 10
        max_index = len(paginator.page_range)
        
        page = self.request.GET.get('page')
        current_page = int(page) if page else 1
        
        start_index = int((current_page -1 ) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index
        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range
        
        context['boardName'] = self.kwargs['boardName']
        context['type'] = search_type
        context['content'] = search_content
        
        return context
    
class PostLikeSearchView(ListView):
    model = Post
    context_object_name = 'posts'
    paginate_by = 20
    template_name = 'board/board_View.html'
    ordering = ['-PostID']
    page_kwarg = 'page'
    
    def get_queryset(self):
        board = Board.objects.get(subject=self.kwargs['boardName'])
        return Post.objects.annotate(num_like=Count('like_user')).filter(board=board,num_like__gte=2)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['board'] = Board.objects.get(subject = self.kwargs['boardName'])

        paginator = context['paginator']
        page_numbers_range = 10
        max_index = len(paginator.page_range)
        
        page = self.request.GET.get('page')
        current_page = int(page) if page else 1
        
        start_index = int((current_page -1 ) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index
        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range
        
        context['boardName'] = self.kwargs['boardName']
        return context
    
class PostDetailView(FormMixin,UpdateModelMixin,DetailView):
    model = Post
    template_name = "post/post_base.html"
    pk_url_kwarg = 'postID'
    context_object_name = 'thePost'
    form_class = CommentForm
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comments = Comment.objects.filter(post=self.object.PostID)
        context['comments'] = comments 
        return context
    
    def get_object(self):
        return get_object_or_404(Post,PostID=self.kwargs['postID'])
    
    def post(self,request,*args,**kwargs):
        self.object = self.get_object()
        form = self.get_form()
        
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
    
    def form_valid(self,form):
        comment = form.save(commit=False)
        comment.post = self.object
        comment.CommentAuthor = self.request.user
        comment.save()  
        self.object.comments += 1
        self.object.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('board:detail', kwargs={'boardName':self.object.board.subject, 'postID':self.object.PostID})
  

class PostLikeView(LoginRequiredMixin,TemplateView):
    model = Post
    template_name = 'post/post_base.html'
    
    def get_object(self):
        return get_object_or_404(Post,PostID=self.kwargs['postID'])
    
    def post(self,request,*arg,**kwargs):
        user = request.user
        self.object = self.get_object()
        if user in self.object.like_user.filter(pk=user.pk):
            self.object.like_user.remove(user)
        else:
            self.object.like_user.add(user)
        return redirect(request.META['HTTP_REFERER'])

 
class PostUpdateView(LoginRequiredMixin,UpdateView):
    model = Post
    form_class = PostForm
    template_name = "board/postCreate.html"
    pk_url_kwarg = 'postID'
    
    def get_object(self):
        return get_object_or_404(Post,PostID=self.kwargs['postID'])
    
    def get_success_url(self):
        return reverse('board:detail', kwargs={'boardName':self.object.board.subject, 'postID':self.object.PostID})
    
class PostDeleteView(LoginRequiredMixin,DeleteView):
    model = Post
    template_name = "post/post_delete.html"
    pk_url_kwarg = 'postID'
    
    def get_success_url(self):
        return reverse('board:aboard', kwargs={'boardName':self.object.board.subject})
    
class CommentCreateView(LoginRequiredMixin,CreateView):
    model = Comment
    form_class = CommentForm
    context_object_name = 'comment'
    template_name = 'comment/comment_base.html'
    
    def form_valid(self, form):
        form.instance.CommentAuthor = self.request.user
        form.instance.post = self.kwargs['postID']
        PP = Post.objects.get(postID= self.kwargs['postID'])
        PP.comments += 1
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('board:detail', kwargs={'boardName':self.kwargs['boardName'],'postID': self.kwargs['postID']})
    
class CommentUpdateView(LoginRequiredMixin,UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = "comment/comment_edit.html"
    
    def get_object(self):
        return get_object_or_404(Comment,CommentID=self.kwargs["commentID"])
    
    def get_success_url(self):
        return reverse('board:detail', kwargs={'boardName':self.kwargs['boardName'],'postID': self.kwargs['postID']})

class CommentDeleteView(LoginRequiredMixin,DeleteView):
    model = Comment
    template_name = "comment/comment_delete.html"
    
    def get_object(self):
        return get_object_or_404(Comment,CommentID=self.kwargs["commentID"])
    

django/templates/board/board_View.html
{% extends "base.html" %}
{% load static %}
{% load template_filter %}
{% block content %}
    <div class="navi pl-md-5">
        <div>
            <p class="lead">{{board.subject}} 게시판</p>
            <p class="small">{{board.context}}</p>
        </div>
        <ul class="list-group list-group-horizontal">
            <li class="list-group-item">
                <a  href="{% url 'board:aboard' board.subject %}">목록</a>
            </li>
            <li class="list-group-item">
                <a href="{% url 'board:post' board.subject %}">글쓰기</a>
            </li>
            <li class="list-group-item">
                <a href="{% url 'board:likeSearch' board.subject %}">추천글</a>
            </li>
          </ul>
    </div>
    <div>
        <main class="col-12 py-md-3 pl-md-5 bd-content" role="main">
          <table class="table table-hover table-bordered overflow-auto">
              <thead class="table-dark">
                  <th style="width: 6%">
                      글번호
                  </th>
                  <th style="width: 50%">
                      제목
                  </th>
                  <th style="width: 15%">
                      작성자
                  </th>
                  <th style="width: 18%">
                      작성시간
                  </th>
                  <th style="width: 5%">
                      조회
                  </th>
                  <th style="width: 5%">
                      추천
                  </th>
              </thead>
          
          {% if posts %}
              <tbody>
              {% for post in posts %}
                  <tr>
                      <td class="rowNum">
                            {{paginator.count|sub:forloop.counter0}} 
                      </td>
                      <td class="rowTitle">
                        {% if post.count_like >= 2 %}
                        <img src="{% static 'assets/star.svg' %}" width="15" height="15" class="d-inline-block" alt="" class="icon">
                        {% endif %}
                          <a href="{% url 'board:detail' boardName=board.subject postID=post.pk  %}">{{post.title}}   [{{post.comments}}]</a>
                      </td>
                      <td class="rowAuthor">
                        {% if post.PostAuthor == post.board.principal %}
                        <img src="{% static 'assets/flower1.svg' %}" width="15" height="15" class="d-inline-block" alt="" class="icon">
                        {% endif %}
                          <a href="{% url 'user:userInfo' post.PostAuthor.nickname %}">{{post.PostAuthor.nickname}}</a> 
                      </td>
                      <td class="rowTime">
                          {{post.writeDate}}
                      </td>
                      <td class="rowViews">
                          {{post.views}}
                      </td>
                      <td class="rowRate">
                          {{post.count_like}}
                      </td>
                  </tr>
              {% endfor %}
              </tbody>
          </table>
          {% else %}
              </tbody>
        </table>
                <p class="text-center">해당되는 포스트가 존재하지 않습니다.</p>
          {% endif %}
          <br>
        
        </main>
          <!-- <div class="container-fluid">
              <div class="row flex-nowrap">
                  <div class="col-3 bd-sidebar">
                      
                      
                  </div>
              </div>
          </div> -->
    </div>
    
    <nav>
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{page_obj.previous_page_number}}">이전</a>
            </li>
            {%else%}
            <li class="page-item disabled">
                <span class="page-link">이전</span>
            </li>
            {% endif %}
            {% for page in page_range %}
            {% if page == page_obj.number  %}
            <li class="page-item active">
                <a class="page-link" href="?page= {{page}}">{{page}}<span class="sr-only">(current)</span></a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page= {{page}}">{{page}}</a>
            </li>
            {% endif %}
            {%endfor%}
      
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link"  href="?page={{page_obj.next_page_number}}">다음</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link">다음</span>
            </li>
            {% endif %}
        </ul>
      </nav>

    <div>
        <form class="form-inline justify-content-center" method="GET" action="{% url 'board:search' board.subject %}">
            <select class="custom-select" id="type" name="t">
                <option value="wide">제목 + 내용</option>
                <option value="title">제목</option>
                <option value="author">글쓴이</option>
            </select>
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="c">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">검색</button>
        </form>
    </div>
    <br>
{% endblock %}

django/templates/board/board_View1.html
{% extends 'board/board_template.html' %}

{% block pagination %}
<nav>
  <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
      <li class="page-item">
          <a class="page-link" href="?page={{page_obj.previous_page_number}}">이전</a>
      </li>
      {%else%}
      <li class="page-item disabled">
          <span class="page-link">이전</span>
      </li>
      {% endif %}
      {% for page in page_range %}
      {% if page == page_obj.number  %}
      <li class="page-item active">
          <a class="page-link" href="?page= {{page}}">{{page}}<span class="sr-only">(current)</span></a>
      </li>
      {% else %}
      <li class="page-item">
          <a class="page-link" href="?page= {{page}}">{{page}}</a>
      </li>
      {% endif %}
      {%endfor%}

      {% if page_obj.has_next %}
      <li class="page-item">
          <a class="page-link"  href="?page={{page_obj.next_page_number}}">다음</a>
      </li>
      {% else %}
      <li class="page-item disabled">
          <span class="page-link">다음</span>
      </li>
      {% endif %}
  </ul>
</nav>
{% endblock %}

django/templates/board/board_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<nav class="bg-primary bg-gradient text-white">
    <div class="container px-4 text-center">
        <h1 class="fw-bolder">게시판홈 </h1>
        <p class="lead">원하는 게시판을 생성하고, 접속할 수 있습니다.</p>
        <p><a class="text-white " href="{% url 'board:create'%}">
            <img src="{% static 'assets/arrow-right-circle.svg' %}" width="20" height="20" class="d-inline-block" alt="" class="icon" id="logo">게시판 생성</a>
        </p>
    </div>
</nav>

<div class="container col-9">
    <ul class="list-group">
    {% if BoardList %}
        {% for board in BoardList %}
        <li class="list-group-item list-group-item-light">
            <div class="boardList" >
                <span class="h3">
                    <a href = "{% url 'board:aboard' board.subject %}" >{{board.subject}}</a> 
                </span>
                <span class="mx-auto">
                    <a href ="{% url 'user:userInfo' board.principal.nickname %}"> 
                        <img src="{% static 'assets/flower1.svg' %}" width="15" height="15" class="d-inline-block" alt="" class="icon"> {{board.principal.nickname}}</a>
                </span>
                <p class="mx-auto">
                        {{board.context}} 
                </p>    
            </div>
        </li>
        {% endfor %}
            
    {% else %}
    <li class="list-group-item list-group-item-light">
        <div class="boardList text-center">
            <p> 현재 생성된 게시판이 없습니다.</p>
        </div>
    </li>
    {% endif %}
    </ul>
</div>
{% endblock %}

django/templates/board/board_search.html
{% extends "base.html" %}
{% load static %}
{% load template_filter %}
{% block content %}
    <div class="navi pl-md-5">
        <div>
            <p class="lead">{{board.subject}} 게시판</p>
            <p class="small">{{board.context}}</p>
        </div>
        <ul class="list-group list-group-horizontal">
            <li class="list-group-item">
                <a  href="{% url 'board:aboard' board.subject %}">목록</a>
            </li>
            <li class="list-group-item">
                <a href="{% url 'board:post' board.subject %}">글쓰기</a>
            </li>
            <li class="list-group-item">
                <a href="{% url 'board:likeSearch' board.subject %}">추천글</a>
            </li>
          </ul>
    </div>
    <div>
        <main class="col-9 py-md-3 pl-md-5 bd-content" role="main">
          <table class="table table-hover table-bordered overflow-auto">
              <thead class="table-dark">
                  <th style="width: 6%">
                      글번호
                  </th>
                  <th style="width: 50%">
                      제목
                  </th>
                  <th style="width: 15%">
                      작성자
                  </th>
                  <th style="width: 18%">
                      작성시간
                  </th>
                  <th style="width: 5%">
                      조회
                  </th>
                  <th style="width: 5%">
                      추천
                  </th>
              </thead>
          
          {% if posts %}
              <tbody>
              {% for post in posts %}
                  <tr>
                      <td class="rowNum">
                            {{paginator.count|sub:forloop.counter0}} 
                      </td>
                      <td class="rowTitle">
                        {% if post.count_like >= 2 %}
                        <img src="{% static 'assets/star.svg' %}" width="15" height="15" class="d-inline-block" alt="" class="icon">
                        {% endif %}
                          <a href="{% url 'board:detail' boardName=board.subject postID=post.pk  %}">{{post.title}}   [{{post.comments}}]</a>
                      </td>
                      <td class="rowAuthor">
                        {% if post.PostAuthor == post.board.principal %}
                        <img src="{% static 'assets/flower1.svg' %}" width="15" height="15" class="d-inline-block" alt="" class="icon">
                        {% endif %}
                          <a href="{% url 'user:userInfo' post.PostAuthor.nickname %}">{{post.PostAuthor.nickname}}</a> 
                      </td>
                      <td class="rowTime">
                          {{post.writeDate}}
                      </td>
                      <td class="rowViews">
                          {{post.views}}
                      </td>
                      <td class="rowRate">
                          {{post.count_like}}
                      </td>
                  </tr>
              {% endfor %}
              </tbody>
          </table>
          {% else %}
              </tbody>
        </table>
                <p class="text-center">해당되는 포스트가 존재하지 않습니다.</p>
          {% endif %}
          <br>
        </main>
          <div class="container-fluid">
              <div class="row flex-nowrap">
                  <div class="col-3 bd-sidebar">
                      
                      
                  </div>
              </div>
          </div>
    </div>
    
    <nav>
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?t={{type}}&c={{content}}&page={{page_obj.previous_page_number}}">이전</a>
            </li>
            {%else%}
            <li class="page-item disabled">
                <span class="page-link">이전</span>
            </li>
            {% endif %}
            {% for page in page_range %}
            {% if page == page_obj.number  %}
            <li class="page-item active">
                <a class="page-link" href="?t={{type}}&c={{content}}&page= {{page}}">{{page}}<span class="sr-only">(current)</span></a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?t={{type}}&c={{content}}&page= {{page}}">{{page}}</a>
            </li>
            {% endif %}
            {%endfor%}
    
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link"  href="?t={{type}}&c={{content}}&page={{page_obj.next_page_number}}">다음</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link">다음</span>
            </li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

django/templates/board/create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="form-group text-center" style="float: none; margin:100 auto;">
    <div class="col-md-3" style="float: none; margin:0 auto;">
        <form action="" method="POST" class="form-signin">
            <h1 class="h3  mt-5 mb-3 font-weight-normal">게시판 생성</h1>
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-lg mt-3 btn-primary btn-block">게시판 생성</button>
            <input type=button class="btn btn-lg mt-3 btn-primary btn-block" value="취소하기" onClick="javascript:history.go(-1);">
        </form>
    </div>
</div>
{% endblock %}

django/templates/board/postCreate.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="form-group text-center mt-2" >
    <div class="col-9" >
        <form action="" method="POST" class="form-signin">
            <h1 class="h3 mt2 font-weight-normal">포스트 작성</h1>
            {% csrf_token %}
            {{ form.as_table }}
            <div class="btn-group float-right" role="group">
                <input type=button class="btn mt-3 btn-danger " value="취소하기" onClick="javascript:history.go(-1);">
                <button type="submit" class="btn mt-3 btn-primary">포스트 작성</button>         
            </div>
            
        </form>
    </div>
</div>
{% endblock %}